apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/dns-forwarding-managed-zone/v0.2.0-alpha.1
    cnrm.cloud.google.com/disable-on-destroy: "false"
    cnrm.cloud.google.com/project-id: project-id # {"$kpt-set":"project-id"}
  name: project-id-dns # {"$kpt-set":"services-dns"}
  namespace: projects
spec:
  resourceID: dns.googleapis.com
