apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/csr-git-ops-pipeline/v0.2.0-alpha.1
    cnrm.cloud.google.com/project-id: project-id # {"$kpt-set":"project-id"}
  name: sourcerepo.googleapis.com
  namespace: config-control # {"$kpt-set":"namespace"}
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/csr-git-ops-pipeline/v0.2.0-alpha.1
    cnrm.cloud.google.com/project-id: project-id # {"$kpt-set":"project-id"}
  name: cloudbuild.googleapis.com
  namespace: config-control # {"$kpt-set":"namespace"}
