apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/disable-on-destroy: "false"
  name: compute.googleapis.com
  namespace: network-namespace # {"$kpt-set":"network-namespace"}
