apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/disable-on-destroy: "false"
    cnrm.cloud.google.com/project-id: project-id # {"$kpt-set":"project-id"}
  name: compute.googleapis.com
  namespace: projects
